profiles:
  active:
    - dev

---

server:
  port: 7001
spring:
  profiles: dev
  application:
    name: application-config-eureka
eureka:
  instance:
    hostname: erueka7001.com
  client:
    register-with-eureka: false  #表示不向注册中心注册自己
    fetch-registry: false   #表示自己就是注册中心，我的职责就是维护服务实现，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://erueka7002.com:7002/eureka/,http://erueka7003.com:7003/eureka/
      #设置于Eureka Server交互的地址，查询服务和注册服务

---
server:
  port: 7002
spring:
  profiles: test
  application:
    name: application-config-eureka
eureka:
  instance:
    hostname: erueka7001.com
  client:
    register-with-eureka: false  #表示不向注册中心注册自己
    fetch-registry: false   #表示自己就是注册中心，我的职责就是维护服务实现，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://erueka7001.com:7001/eureka/,http://erueka7003.com:7003/eureka/
      #设置于Eureka Server交互的地址，查询服务和注册服务
